plugins {
    id "com.android.application"
}

android {
    namespace "com.jack80apptest.priceguard"
    compileSdk 36

    defaultConfig {
        applicationId "com.jack80apptest.priceguard"
        minSdk 23
        targetSdk 36
        versionCode 3
        versionName "0.1.2"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}

dependencies {
    implementation "androidx.activity:activity:1.10.1"
    implementation "androidx.core:core:1.16.0"
}
